version: '0.0.1-SNAPSHOT'
services:
  mysql-standalone:
    image: 'mysql:8'
    environment:
      - MYSQL_ROOT_PASSWORD=root.
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=e_coteriedb
    ports:
    - "3307:3306"
    volumes:
    - mysql-data: /var/lib/mysql
  springboot-docker-container:
    image: springboot-docker-container
    ports:
    - "8090:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/e_coteriedb?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root."
    build:
      context: "./"
      dockerfile: "Dockerfile"
    depends_on:
      - mysql-standalone
volumes:
  mysql-data: